
DELETE http://localhost:3003/api/blogs/61f5e5d8cd1256e8f37f40ff HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNlbGluYVp6eiIsImlkIjoiNjFmNWI0ZTNlY2YwY2YwOWUyNTQ5MDgzIiwiaWF0IjoxNjQzNTA0NjgyfQ.72DI7yr7OqgwWO69VINc9-6Nj9y16quMNO5nlsDPa8Y
###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "The makings of a great cook",
    "author": "GordonRamseee",
    "url": "http://i-am-a-great-cook.com",
    "likes": 882345
}