PUT http://localhost:3003/api/blogs/61f5c53524cb45a83225d17b HTTP/1.1
content-type: application/json

{
    "title": "How to come up with blog titles",
    "author": "Heythere",
    "url": "http://aaaah.com",
    "likes": 20, 
    "comments": ["nice", "good one"]
}